/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package vue;

import controleur.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author btssio
 */


public class VueVisiteur extends VueAbstraite { 

    private DefaultComboBoxModel modeleJComboBoxVisiteur; 
    private DefaultComboBoxModel modeleJComboBoxSecteur;
    private DefaultComboBoxModel modeleJComboBoxLaboratoire;
    
    
    public VueVisiteur(CtrlAbstrait ctrl) {
        super(ctrl);
        initComponents();
        this.setLocation(500, 200);
        
        
        // Liste visiteur
        modeleJComboBoxVisiteur = new DefaultComboBoxModel();
        jComboBoxListeVisiteurs.setModel(modeleJComboBoxVisiteur);
        // Liste secteur
        modeleJComboBoxSecteur = new DefaultComboBoxModel();
        jComboBoxSecteurVisiteur.setModel(modeleJComboBoxSecteur);
        // Liste Laboratoire
        modeleJComboBoxLaboratoire = new DefaultComboBoxModel();
        jComboBoxLaboratoireVisiteur.setModel(modeleJComboBoxLaboratoire);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonChercherVisiteur = new javax.swing.JButton();
        jComboBoxListeVisiteurs = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomVisiteur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrenomVisiteur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldVilleVisiteur = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCodePostalVisiteur = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxSecteurVisiteur = new javax.swing.JComboBox();
        jComboBoxLaboratoireVisiteur = new javax.swing.JComboBox();
        jTextFieldAdresseVisiteur = new javax.swing.JTextField();
        jButtonSuivantVisiteur = new javax.swing.JButton();
        jButtonPrecedentVisiteur = new javax.swing.JButton();
        jButtonRetourMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(484, 666));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 1, 36)); // NOI18N
        jLabel1.setText("Visiteurs");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonChercherVisiteur.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jButtonChercherVisiteur.setText("Chercher");
        jButtonChercherVisiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChercherVisiteurActionPerformed(evt);
            }
        });

        jComboBoxListeVisiteurs.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jComboBoxListeVisiteurs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxListeVisiteurs, 0, 177, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonChercherVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxListeVisiteurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChercherVisiteur))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 3, 15)); // NOI18N
        jLabel2.setText("Rechercher un visiteur : ");

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 3, 15)); // NOI18N
        jLabel9.setText("Détails visiteurs :");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/Images/utilisateur-icone-9647-96.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jLabel3.setText("Nom : ");

        jTextFieldNomVisiteur.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jLabel4.setText("Prénom :");

        jTextFieldPrenomVisiteur.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jLabel5.setText("Adresse :");

        jLabel6.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jLabel6.setText("Ville :");

        jTextFieldVilleVisiteur.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jLabel11.setText("Code postal :");

        jTextFieldCodePostalVisiteur.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jLabel7.setText("Secteur :");

        jLabel8.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jLabel8.setText("Laboratoire : ");

        jComboBoxSecteurVisiteur.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jComboBoxSecteurVisiteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxLaboratoireVisiteur.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jComboBoxLaboratoireVisiteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldAdresseVisiteur.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N

        jButtonSuivantVisiteur.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jButtonSuivantVisiteur.setText("Suivant");
        jButtonSuivantVisiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuivantVisiteurActionPerformed(evt);
            }
        });

        jButtonPrecedentVisiteur.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jButtonPrecedentVisiteur.setText("Précèdent");
        jButtonPrecedentVisiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrecedentVisiteurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addComponent(jButtonPrecedentVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSuivantVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodePostalVisiteur)
                            .addComponent(jTextFieldAdresseVisiteur)
                            .addComponent(jTextFieldVilleVisiteur, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNomVisiteur)
                            .addComponent(jTextFieldPrenomVisiteur)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxLaboratoireVisiteur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxSecteurVisiteur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPrenomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAdresseVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldVilleVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCodePostalVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxSecteurVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxLaboratoireVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrecedentVisiteur)
                    .addComponent(jButtonSuivantVisiteur))
                .addGap(21, 21, 21))
        );

        jButtonRetourMenu.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jButtonRetourMenu.setText("Revenir au Menu");
        jButtonRetourMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonRetourMenu)
                        .addGap(172, 172, 172))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRetourMenu)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetourMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourMenuActionPerformed
        try {
            ((CtrlVisiteur)controleur).retourMenu();
        } catch (Exception ex) {
            Logger.getLogger(VueVisiteur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRetourMenuActionPerformed

    private void jButtonChercherVisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChercherVisiteurActionPerformed
        ((CtrlVisiteur)controleur).ChercherUnVisiteur();
    }//GEN-LAST:event_jButtonChercherVisiteurActionPerformed

    private void jButtonPrecedentVisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrecedentVisiteurActionPerformed
        ((CtrlVisiteur)controleur).Precedent();
    }//GEN-LAST:event_jButtonPrecedentVisiteurActionPerformed

    private void jButtonSuivantVisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuivantVisiteurActionPerformed
        ((CtrlVisiteur)controleur).Suivant();
    }//GEN-LAST:event_jButtonSuivantVisiteurActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            ((CtrlVisiteur)controleur).fichierQuitter();
        } catch (Exception ex) {
            Logger.getLogger(VueVisiteur.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowClosing
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChercherVisiteur;
    private javax.swing.JButton jButtonPrecedentVisiteur;
    private javax.swing.JButton jButtonRetourMenu;
    private javax.swing.JButton jButtonSuivantVisiteur;
    private javax.swing.JComboBox jComboBoxLaboratoireVisiteur;
    private javax.swing.JComboBox jComboBoxListeVisiteurs;
    private javax.swing.JComboBox jComboBoxSecteurVisiteur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAdresseVisiteur;
    private javax.swing.JTextField jTextFieldCodePostalVisiteur;
    private javax.swing.JTextField jTextFieldNomVisiteur;
    private javax.swing.JTextField jTextFieldPrenomVisiteur;
    private javax.swing.JTextField jTextFieldVilleVisiteur;
    // End of variables declaration//GEN-END:variables

// GETTER & SETTERS de la vue
    
     public DefaultComboBoxModel getModeleJComboBoxVisiteur() {
        return modeleJComboBoxVisiteur;
    }

    public void setModeleJComboBoxVisiteur(DefaultComboBoxModel modeleJComboBoxVisiteur) {
        this.modeleJComboBoxVisiteur = modeleJComboBoxVisiteur;
    }

    public DefaultComboBoxModel getModeleJComboBoxSecteur() {
        return modeleJComboBoxSecteur;
    }

    public void setModeleJComboBoxSecteur(DefaultComboBoxModel modeleJComboBoxSecteur) {
        this.modeleJComboBoxSecteur = modeleJComboBoxSecteur;
    }

    public DefaultComboBoxModel getModeleJComboBoxLaboratoire() {
        return modeleJComboBoxLaboratoire;
    }

    public void setModeleJComboBoxLaboratoire(DefaultComboBoxModel modeleJComboBoxLaboratoire) {
        this.modeleJComboBoxLaboratoire = modeleJComboBoxLaboratoire;
    }

    public JButton getjButtonChercherVisiteur() {
        return jButtonChercherVisiteur;
    }

    public void setjButtonChercherVisiteur(JButton jButtonChercherVisiteur) {
        this.jButtonChercherVisiteur = jButtonChercherVisiteur;
    }

    public JButton getjButtonPrecedentVisiteur() {
        return jButtonPrecedentVisiteur;
    }

    public void setjButtonPrecedentVisiteur(JButton jButtonPrecedentVisiteur) {
        this.jButtonPrecedentVisiteur = jButtonPrecedentVisiteur;
    }

    public JButton getjButtonSuivantVisiteur() {
        return jButtonSuivantVisiteur;
    }

    public void setjButtonSuivantVisiteur(JButton jButtonSuivantVisiteur) {
        this.jButtonSuivantVisiteur = jButtonSuivantVisiteur;
    }

    public JComboBox getjComboBoxLaboratoireVisiteur() {
        return jComboBoxLaboratoireVisiteur;
    }

    public void setjComboBoxLaboratoireVisiteur(JComboBox jComboBoxLaboratoireVisiteur) {
        this.jComboBoxLaboratoireVisiteur = jComboBoxLaboratoireVisiteur;
    }

    public JComboBox getjComboBoxListeVisiteurs() {
        return jComboBoxListeVisiteurs;
    }

    public void setjComboBoxListeVisiteurs(JComboBox jComboBoxListeVisiteurs) {
        this.jComboBoxListeVisiteurs = jComboBoxListeVisiteurs;
    }

    public JComboBox getjComboBoxSecteurVisiteur() {
        return jComboBoxSecteurVisiteur;
    }

    public void setjComboBoxSecteurVisiteur(JComboBox jComboBoxSecteurVisiteur) {
        this.jComboBoxSecteurVisiteur = jComboBoxSecteurVisiteur;
    }

    public JTextField getjTextFieldAdresseVisiteur() {
        return jTextFieldAdresseVisiteur;
    }

    public void setjTextFieldAdresseVisiteur(JTextField jTextFieldAdresseVisiteur) {
        this.jTextFieldAdresseVisiteur = jTextFieldAdresseVisiteur;
    }

    public JTextField getjTextFieldCodePostalVisiteur() {
        return jTextFieldCodePostalVisiteur;
    }

    public void setjTextFieldCodePostalVisiteur(JTextField jTextFieldCodePostalVisiteur) {
        this.jTextFieldCodePostalVisiteur = jTextFieldCodePostalVisiteur;
    }

    public JTextField getjTextFieldNomVisiteur() {
        return jTextFieldNomVisiteur;
    }

    public void setjTextFieldNomVisiteur(JTextField jTextFieldNomVisiteur) {
        this.jTextFieldNomVisiteur = jTextFieldNomVisiteur;
    }

    public JTextField getjTextFieldPrenomVisiteur() {
        return jTextFieldPrenomVisiteur;
    }

    public void setjTextFieldPrenomVisiteur(JTextField jTextFieldPrenomVisiteur) {
        this.jTextFieldPrenomVisiteur = jTextFieldPrenomVisiteur;
    }

    public JTextField getjTextFieldVilleVisiteur() {
        return jTextFieldVilleVisiteur;
    }

    public void setjTextFieldVilleVisiteur(JTextField jTextFieldVilleVisiteur) {
        this.jTextFieldVilleVisiteur = jTextFieldVilleVisiteur;
    }

}

